# This pipeline assumes that there is a Conda environment AzureRunner already.
# It will run pytest, and publish the test results.
steps:
  # The run ID of the training run is now available in training_run.txt. Move that back to the default runID name,
  # and run all tests that build upon that training run.
  - bash: |
      source activate AzureRunner
      pytest ./Tests/ -m "after_training" --junitxml=junit/test-results-after-training.xml
    env:
      PYTHONPATH: $(Build.SourcesDirectory)
      APPLICATION_KEY: $(InnerEyeDeepLearningServicePrincipalKey)
    displayName: Run pytests that require training run

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: junit/test-results-after-training.xml
      testRunTitle: ${{parameters.test_run_title}}
    condition: succeededOrFailed()
    displayName: Publish test results ${{parameters.test_run_title}}
